### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Clauber** [capawesome-team/capacitor-app-update#51] opened 2022-08-23 00:40 UTC
**Plugin version:**
2.0

**Platform(s):**
Android

**Current behavior:**
Does not build

**Expected behavior:**
Plugin to build

**Steps to reproduce:**
Create Ionic App with react, install your plugin and try to build for android

**Related code:**

```
insert short code snippets here
```

**Other information:**
Here is a screenshot of the error I get
![image](https://user-images.githubusercontent.com/11656515/186043536-50f55d47-9ed1-4b84-9728-93da6e8c3b10.png)

**Capacitor doctor:**

```
npx cap doctor
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 4.1.0
  @capacitor/core: 4.1.0
  @capacitor/android: 4.1.0
  @capacitor/ios: 4.1.0

Installed Dependencies:

  @capacitor/cli: 3.7.0
  @capacitor/android: 3.7.0
  @capacitor/core: 3.7.0
  @capacitor/ios: 3.7.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment] 2022-08-23 05:45
I close this issue as duplicate of https://github.com/ionic-team/capacitor/issues/5824.
Let me know if the problem persists.

**Closed** 2022-08-23 05:45 UTC
