### ISSUE TITLE
iOS Issue:  Required app information could not be fetched

### ISSUE THREAD

**Issue by connectMyClub** [capawesome-team/capacitor-app-update#52] opened 2022-09-17 13:25 UTC
The plugin returns the information as expected in Android build but we are seeing an error on iOS (real device and simulator)

`AppUpdate.getAppUpdateInfo: message: "Required app information could not be fetched"`
`Error: Uncaught (in promise): Error: Required app information could not be fetched CapacitorException@capacitor://localhost/vendor.js:1500:10`

Code below
```
import {  AppUpdate, AppUpdateInfo } from '@capawesome/capacitor-app-update';

public appUpdateInfo: AppUpdateInfo | undefined;

 ngOnInit() {

      AppUpdate.getAppUpdateInfo().then(appUpdateInfo => {
            this.appUpdateInfo = appUpdateInfo;
            if( this.appUpdateInfo.updateAvailability === 2){
              this.openAppStore();
            }
          });

}
```

**Comment by robingenz** [comment] 2022-09-17 13:58
This issue seems like a duplicate of #19. For this reason I am closing this issue. Let me know if your problem persists.

**Closed** 2022-09-17 13:59 UTC
Labels: duplicate

**Comment by connectMyClub** [comment] 2022-09-17 14:36
Ah, so the plugin won't work with locally installed apps, only ones installed from the app store? Our app is now live on the app store so hopefully we will see the issue will resolve when I release an update. the app I was working with was a dev version installed from XCode.

**Comment by robingenz** [comment] 2022-09-17 15:24
It works with a locally installed app on iOS if the app identifier is the same as in the AppStore (without dev suffix etc.).

**Comment by connectMyClub** [comment] 2022-09-17 16:40
Brilliant, thank you

Great plugin.

**Comment by connectMyClub** [comment] 2022-09-18 10:54
Found the issue by following the previous issue threads.

Our app is only available in the UK (gb) so without the GB country code
nothing is returned
https://itunes.apple.com/lookup?bundleId=com.connectmyclub.app but it is
with the country code.
https://itunes.apple.com/lookup?bundleId=com.connectmyclub.app&country=gb


Paul Curtis

*connectMyClub*

h ***@***.******@***.***
***@***.***>

connectMyClub.co.uk <http://connectmyclub.co.uk/>

**Comment by robingenz** [comment] 2022-09-18 12:22
You can pass the country when calling 'getAppUpdateInfo' (see readme).

**Comment by connectMyClub** [comment] 2022-09-18 12:54
Thanks. I've done that already now I understand the docs more fully. Thank you
